/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buscaminas;

import java.awt.Toolkit;
import javax.swing.JOptionPane;



/**
 *
 * @author fimaz
 */
public class personalizado extends javax.swing.JFrame {

    
    
    public personalizado() {
        
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../images/icono.png")));
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMinas = new javax.swing.JTextField();
        txtFilas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtColumnas = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBack = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Mines");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 82, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 147, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Custom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 316, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Rows");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 122, -1, -1));

        txtMinas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtMinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 87, 106, -1));

        txtFilas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 127, 106, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Colums");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 162, -1, -1));

        txtColumnas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 166, 106, -1));

        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inicio1.png"))); // NOI18N
        btnStart.setContentAreaFilled(false);
        btnStart.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inicio2.png"))); // NOI18N
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 197, -1, 64));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FONDO.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, -22, 330, 290));

        menuBack.setText("<- Back");
        menuBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBackMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuBack);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        
        String minas, filas,columnas;
        int minasCast, filasCast, columnasCast;
        minas = txtMinas.getText();
        filas = txtFilas.getText();
        columnas = txtColumnas.getText();
        
        
        
            if(minas.isEmpty() || filas.isEmpty() || columnas.isEmpty()){
            JOptionPane.showMessageDialog(null,"¡ERROR! Please complete all fields. ");
            }else{
                minasCast = Integer.parseInt(txtMinas.getText());
                filasCast = Integer.parseInt(txtFilas.getText());
                columnasCast = Integer.parseInt(txtColumnas.getText());
                //Validamos que las minas sean >=1 y < al tamaño del tablero
                if(minasCast <= 0){
                    JOptionPane.showMessageDialog(null,"¡ERROR! You need more mines. ");
                }else{
                
                    if(minasCast == (filasCast * columnasCast) ){
                        JOptionPane.showMessageDialog(null,"¡ERROR! A lot of mines. ");
                    }else{
                        int nMinas, nFilas, nColumnas;

                        nMinas =Integer.parseInt(txtMinas.getText());
                        nFilas =Integer.parseInt(txtFilas.getText());
                        nColumnas =Integer.parseInt(txtColumnas.getText());

                        System.out.println("minas "+nMinas);
                        System.out.println("filas "+nFilas);
                        System.out.println("columnas "+nColumnas);


                        panelMinas obj = new panelMinas();
                        obj.llenarPanel(nMinas, nFilas, nColumnas);
                        obj.gMinas=nMinas;
                        obj.gFilas=nFilas;
                        obj.gColumnas=nColumnas;

                        obj.setVisible(true);
                    }
                
            }
            }
    }//GEN-LAST:event_btnStartActionPerformed

    private void menuBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBackMouseClicked
        
            mainMenu obj = new mainMenu();
            obj.setVisible(true);
            setVisible(false);
        
    }//GEN-LAST:event_menuBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personalizado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuBack;
    private javax.swing.JTextField txtColumnas;
    private javax.swing.JTextField txtFilas;
    private javax.swing.JTextField txtMinas;
    // End of variables declaration//GEN-END:variables
}
